apiVersion: apps/v1beta2　　　　
kind: Deployment　　　　　　　　　　
metadata:
  name: asktest　　　　　　　　
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asktest
  template:
    metadata:
      labels:
        app: asktest　　　　
    spec:
      containers:
      - name: asktest　　　　
        image: askhub.azurecr.io/image-workflow-1689606550537　　
        ports:
        - containerPort: 1000　　　　
        env:
        - name: serverport
          value: "1000"